### PR TITLE
Add coordinates, remove NSEW fields.

### PR DESCRIPTION
**Pull request by AaronCMuller**
@danielbaker @yetti @scoen @MingtaoSun

### CODE REVIEW

**Comment by MingtaoSun** [comment]
ok :+1:

**Comment by scoen** [comment]
looks good. i guess we could clean up the existing properties in the dbs too

**Comment by AaronCMuller** [comment]
@scoen I was planning to do that as part of a banjo migration.

**Comment by scoen** [comment]
sounds good

**Comment by MingtaoSun** [comment]
@AaronCMuller , Hi Aaron, I wonder when you are going to put in the banjo side of change. There is compilation error in WorkFields when I update pom version to 1.6.4

**Comment by AaronCMuller** [comment]
@MingtaoSun Hopefully this week. Do you need to upgrade to 1.6.4 or later?

**Comment by MingtaoSun** [comment]
No, not necessarily. I can do with 1.6.3.
